### ISSUE TITLE
[Frontend] Results Page

### ISSUE THREAD

**Issue by nathanchiu888** [nathanchiu888/ecs-171-project#9]
**Description:**

The results page will display the fire prediction results after the user submits the data on the home page. The page will call an endpoint that returns the prediction results, and then present them results on this page.

**Tasks:**

- [ ] Set up the results page (`/results`) to display the prediction results.
- [ ] Display the fire prediction results in a clear map view.
  - Show expected fire growth for x number of timesteps
  - Slider for timesteps on map view
- [ ] Add a loading indicator while the prediction is being processed.
- [ ] Display any error messages if the prediction fails or if there is invalid input.
- [ ] Allow the user to return to the home page or input new data.

**Expected Outcome:**

A results page that calls the prediction endpoint and displays the fire prediction results in a clear manner (maybe looks nice too :)).
